"""updated model

Revision ID: 56bbb0c8ebd5
Revises: 937eb97607e4
Create Date: 2023-05-05 13:40:36.772419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bbb0c8ebd5'
down_revision = '937eb97607e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
