"""models

Revision ID: 937eb97607e4
Revises: c4d7f9729c0f
Create Date: 2023-05-05 09:36:36.108125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937eb97607e4'
down_revision = 'c4d7f9729c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clublevel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platinum', sa.String(length=255), nullable=False),
    sa.Column('gold', sa.String(length=255), nullable=False),
    sa.Column('silver', sa.String(length=255), nullable=False),
    sa.Column('bronze', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mypayment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_owed', sa.Float(), nullable=True),
    sa.Column('billing_cycle', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_preference', sa.String(length=255), nullable=False),
    sa.Column('Budget', sa.Float(), nullable=True),
    sa.Column('nationality', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('club_level', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('club_level')
        batch_op.drop_column('address')

    op.drop_table('survey')
    op.drop_table('mypayment_history')
    op.drop_table('clublevel')
    op.drop_table('administrator')
    # ### end Alembic commands ###
